# Generated by Django 4.2.7 on 2025-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='notify_new_bookings',
            field=models.BooleanField(default=True, help_text='Notify about new bookings', verbose_name='New Bookings'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='notify_payments',
            field=models.BooleanField(default=True, help_text='Notify about payment activities', verbose_name='Payments'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='notify_system_updates',
            field=models.BooleanField(default=True, help_text='Notify about system updates and maintenance', verbose_name='System Updates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has verified their account', verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +252612345678', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a clear photo of yourself', null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications via email', verbose_name='Email Notifications'),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Receive push notifications when using the app', verbose_name='Push Notifications'),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Receive notifications via SMS (requires valid phone number)', verbose_name='SMS Notifications'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Your current address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Name of person to contact in case of emergency', max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='accounts_cu_usernam_ab560e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='accounts_cu_user_ty_97b0bf_idx'),
        ),
    ]
