# Generated by Django 4.2.7 on 2025-06-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_alter_userprofile_options_customuser_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_usernam_ab560e_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_email_5ce40b_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_user_ty_97b0bf_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='notify_new_bookings',
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='notify_payments',
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='notify_system_updates',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email Notifications'),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='Push Notifications'),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='sms_notifications',
            field=models.BooleanField(default=True, verbose_name='SMS Notifications'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone'),
        ),
    ]
