# Generated by Django 4.2.7 on 2025-06-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_options_and_more'),
    ]

    operations = [
    ]
