# Generated by Django 5.2.4 on 2025-07-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_handle_uploaded_by_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('TOURIST', 'Tourist'), ('GUIDE', 'Tour Guide'), ('ADMIN', 'System Admin')], default='TOURIST', max_length=10, verbose_name='User Type'),
        ),
    ]
