# Generated by Django 4.2.7 on 2025-06-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Destination Image', 'verbose_name_plural': 'Destination Images'},
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
