# Generated by Django 4.2.7 on 2025-06-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_alter_destinationimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailabilityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_periods', to='tms.tourguide')),
            ],
            options={
                'verbose_name': 'Unavailability Period',
                'verbose_name_plural': 'Unavailability Periods',
                'ordering': ['start_date'],
            },
        ),
    ]
