# Generated by Django 4.2.7 on 2025-06-23 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_unavailabilityperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Daily Rate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Year'),
        ),
    ]
