# Generated by Django 4.2.7 on 2025-06-23 04:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_remove_vehicle_created_at_remove_vehicle_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationimage',
            options={'ordering': ['-is_featured', 'created_at'], 'verbose_name': 'Accommodation Image', 'verbose_name_plural': 'Accommodation Images'},
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='images',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='accommodationimage',
            name='accommodation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tms.accommodation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodationimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Room Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price per Night')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('features', models.TextField(blank=True, verbose_name='Features')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='tms.accommodation')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['price_per_night'],
            },
        ),
    ]
